In [21]:
import numpy as np
import scipy.ndimage as ndi
np.set_printoptions(suppress=True)

I1 = np.array([
    [5, 0, 0, 1, 2],
    [2, 1, 5, 1, 2],
    [7, 1, 5, 1, 2],
    [7, 4, 5, 4, 3],
    [7, 1, 6, 1, 3]
])

Hx = np.array([
    [-1, 0, 1],
    [-2, 0, 2],
    [-1, 0, 1]
])

Hy = np.array([
    [-1, -2, -1],
    [ 0,  0,  0],
    [ 1,  2,  1]
])



print("1.a.")

sobelx = ndi.convolve(I1, Hx)
sobely = ndi.convolve(I1, Hy)

x, y = 0, 0
print("Gradient vector at ({0}, {1}):".format(x, y), np.array([sobelx[x, y], sobely[x, y]]))
x, y = 1, 1
print("Gradient vector at ({0}, {1}):".format(x, y), np.array([sobelx[x, y], sobely[x, y]]))
x, y = 0, 3
print("Gradient vector at ({0}, {1}):".format(x, y), np.array([sobelx[x, y], sobely[x, y]]))



print("\n\n1.b.")
H = np.zeros(8)
for i in I1.flatten():
    H[i] += 1
H = H/H.sum()
print("Normalized histogram:")
print(H)



print("\n\n1.c.")

hist_c = np.cumsum(H)
hist_c = hist_c/hist_c.max()
target = np.cumsum(np.ones(8))
target = target/target.max()

light = hist_c.copy()
for x in range(len(hist_c)):
    l = np.where(np.abs(target - hist_c[x]) < 1/16)[0]
    if len(l) > 0:
        light[x] = l[0]
I2 = I1.copy()
for r in range(I1.shape[0]):
    for c in range(I1.shape[1]):
        I2[r, c] = light[I2[r, c]]

print("I2:")
print(I2)

newH = np.zeros(8)
for i in I2.flatten():
    newH[i] += 1
newH = newH/newH.sum()
print("New histogram:")
print(newH)

1.a.
Gradient vector at (0, 0): [16  8]
Gradient vector at (1, 1): [ 1 -9]
Gradient vector at (0, 3): [-3 -5]


1.b.
Normalized histogram:
[0.08 0.28 0.16 0.08 0.08 0.16 0.04 0.12]


1.c.
I2:
[[6 0 0 2 3]
 [3 2 6 2 3]
 [7 2 6 2 3]
 [7 4 6 4 4]
 [7 2 6 2 4]]
New histogram:
[0.08 0.   0.28 0.16 0.16 0.   0.2  0.12]


In [22]:
print("2.a.")
N = 2
x = np.tile(np.arange(0, N), (N, 1))
WDFT = np.exp(-2j*np.pi/N*x*x.T) # u = x.T
print("DFT kernel for 2 points:")
print(WDFT, end = "\n\n")
fx = [1, 3]
res = np.matmul(WDFT, fx)
print("DFT result for fx =", fx)
print(res)

print("\n\n2.b.")
N = 4
x = np.tile(np.arange(0, N), (N, 1))
WDCT = np.cos((x + 0.5)*x.T*np.pi/N)*np.sqrt(2/N)
WDCT[0] = WDCT[0]/np.sqrt(1/2)
print("DCT kernel for 4 points:")
print(WDCT, end = "\n\n")
fx = [1, 0, 1]
res = np.matmul(WDCT, fx + [0])
print("DCT result for fx =", fx)
print(res[:-1])


2.a.
DFT kernel for 2 points:
[[ 1.+0.j  1.+0.j]
 [ 1.+0.j -1.-0.j]]

DFT result for fx = [1, 3]
[ 4.+0.j -2.-0.j]


2.b.
DCT kernel for 4 points:
[[ 1.          1.          1.          1.        ]
 [ 0.65328148  0.27059805 -0.27059805 -0.65328148]
 [ 0.5        -0.5        -0.5         0.5       ]
 [ 0.27059805 -0.65328148  0.65328148 -0.27059805]]

DCT result for fx = [1, 0, 1]
[2.         0.38268343 0.        ]


In [23]:
print("3.a.")
translate = np.array([
    [1,  0, -3],
    [0,  1, -3],
    [0,  0,  1]
])

t = np.radians(45)
rotate = np.array([
    [np.cos(t), -np.sin(t), 0],
    [np.sin(t),  np.cos(t), 0],
    [0, 0, 1]
])

itranslate = np.array([
    [1, 0, 3],
    [0, 1, 3],
    [0, 0, 1]
])

resulta = np.matmul(np.matmul(itranslate, rotate), translate)
print("Rotate matrix:")
print(resulta)

print("\n\n3.b.")
import numpy.linalg
x, y = 2, 3
resultb = np.matmul(np.linalg.inv(resulta), [y, x, 1])
resultb = np.round(resultb) # zero-order
print("Source of I({0}, {1}) is".format(x, y))
print(resultb[:-1])

3.a.
Rotate matrix:
[[ 0.70710678 -0.70710678  3.        ]
 [ 0.70710678  0.70710678 -1.24264069]
 [ 0.          0.          1.        ]]


3.b.
Source of I(2, 3) is
[2. 2.]
